### ISSUE TITLE
downlit and GitHub README

### ISSUE THREAD

**Issue by maelle** [r-lib/downlit#26]
how best would one turn on downlit autolinking for GitHub READMEs?

**Comment by maelle** [comment]
(and how would this clash with pkgdown using README.md)

**Comment by hadley** [comment]
We'd need a new document format like `hugodown::md_document()` that only did the autolinking piece (I [looked into](https://github.com/r-lib/downlit/pull/9/files) the highlighting too but github strips all html tags that we could use to change the colours). It shouldn't affect pkgdown, because it's only supposed to link `<code>` tags that contain only text (although I don't know if that's ever been tested).

**Comment by maelle** [comment]
If reprex used that format too (for GitHub as a venue), it'd probably help increase page rank of pkgdown websites by adding more links to them in issues?

**Comment by hadley** [comment]
Now moved to https://github.com/rstudio/rmarkdown/issues/1881
